plugins: rubocop-rspec

AllCops:
  Exclude:
    - "bundle/**/*"
    - "spec/spec_helper.rb"
  NewCops: enable

Layout/LineLength:
  Max: 80

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
