services:
  app:
    build:
      context: .
      target: dev
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
    command: thor app:ai
    volumes:
      - ".:/usr/src/app"
      - bundle:/bundle

volumes:
  bundle:
